# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lead Genius
subtitle: Lead generation by design
email: leads@lead-genius.us
description: Advanced lead generation through design. We talk about landing pages, squeeze pages, blogs, design, layout, and user interface.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lead-genius.us" # the base hostname & protocol for your site
twitter_username: lead_genius
github_username:  lead-genius

# Build settings
markdown: kramdown
